topics = {
    # MATH
    "A": "Algebra",
    "G": "Geometry",
    "T": "Trigonometry",
    "D": "Derivative",
    "I": "Integration",
    "O": "Ordinary Differential Equation",
    "v2": "2-Dimensional Vectors",
    "v3": "3-Dimensional Vectors",
    # 2D Vectors
    "add": "Addition",
    "sub": "Subtraction",
    "dot": "Dot Product",
    "cro": "Cross Product",
    "len": "Length",
    "ang": "Angle",
    "pro": "Projection",
    # Geometry
    "lin": "Line",
    "cir": "Circle",
    "tri": "Triangle",
    "arc": "Arc",
    "are": "Area",
    "vol": "Volume",
    "coa": "Center of Area",
    "moa": "Moment of Area",
    # Physics Definitions
    "for2": "2-Dimensional Forces",
    "mom2": "2-Dimensional Moments",
    "for3": "3-Dimensional Forces",
    "mom3": "3-Dimensional Moments",
    "work": "Work",
    "powe": "Power",
    "coma": "Center of Mass",
    "moin": "Moment of Inertia",
    "velo": "Velocity",
    "spee": "Speed",
    "acce": "Acceleration",
    "angv": "Angular Velocity",
    "anga": "Angular Acceleration",
    "torq": "Torque",
    "temp": "Temperature",
    "cp": "Specific Heat",
    "enth": "Enthalpy",
    "entr": "Entropy",
    "ener": "Energy",
    # Physics Concepts
    "fbd": "Free Body Diagram",
    "eqb2": "2-Dimensional Equilibrium",
    "eqb3": "3-Dimensional Equilibrium",
    "fric": "Friction",
    # Statics Applications
    "trus": "Trusses",
    "mtjt": "Method of Joints",
    "mtsc": "Method of Sections",
    "fram": "Frames",
    "mach": "Machines",
    "wedg": "Wedges",
    "scre": "Screws",
    "belt": "Belts",
    "jour": "Journal Bearings",
    "incp": "Inclined Plane"
}
